# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbcaac21b6feddac2e2e098d89fb3bc779c527ff935aa6b3b28566e10d79500358308ab13832addbd02824332c30f81bb4065bd5f0c45ed4a5ad2785b88e280b

test:
  secret_key_base: db69c5b8b38834ea0364553f85f1ecdb63410a7da116c3c8db293fe7839c333f0b61acad4f79bd623cf9b33125b136900c97544a71a15aabdc934707365c8a65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
